name: Build Python App (GitHub UI)
 
on:
  push:
    branches:
      - main
      - stem1
    # branches-ignore:
    # - "stem1*"
    paths:
       - "src/**"
       - "dependencies.txt"
  schedule:
     - cron: "08 1 * * *"
     
# Trigger when issue events occur
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Rename dependencies file
        run: mv dependencies.txt requirements.txt
 
      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - name: Run Python app
        run: python main.py
